version: '3'
services:
  db:
    build: ./database/
    image: postgres:13.3-alpine
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: "exit 0"

  app:
    build: ./
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      # - 'db'
      db:
        condition: service_healthy
    environment:
        - PORT=4000
